FROM nginx:latest
MAINTAINER Muhammad Surya Ihsanuddin<surya.kejawen@gmail.com>

# Setting Configurations
ENV FASTCGI_HOST    localhost
ENV FASTCGI_PORT    9000

#ADD sites-enabled/site.conf /etc/nginx/conf.d/default.conf
#ADD sites-enabled/php-fpm.conf /etc/nginx/conf.d/php-fpm.conf
#ADD nginx.conf /etc/nginx/nginx.conf
#ADD fastcgi_cache /etc/nginx/fastcgi_cache
#ADD static_files.conf /etc/nginx/static_files.conf
#ADD start.sh /etc/nginx/start.sh
#
#RUN chmod +x /etc/nginx/start.sh
#
#CMD ["/etc/nginx/start.sh"]
